name: fetch and patch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: aeiouaoeiuv/ubuntu:nerd_font_patcher
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Decrypt
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase='${{ secrets.PASSWORD }}' --output src/glyphs/Font\ Awesome\ 5\ Pro-Solid-900.otf src/glyphs/Font\ Awesome\ 5\ Pro-Solid-900.otf.gpg
      -
        name: Build FiraCode
        run: |
          export LC_ALL="en_US.UTF-8"
          mkdir -p firacode
          wget -c ${{ vars.FIRACODE_DOWNLOAD_URL }}
          unzip ${{ vars.FIRACODE_DOWNLOADED_FILENAME }} -d firacode
          ./build.sh -t firacode/ttf -o firacode_patched
      -
        name: Upload FiraCode Artifact
        uses: actions/upload-artifact@v3
        with:
          name: firacode_patched
          path: firacode_patched
      -
        name: Build CascadiaCode
        run: |
          export LC_ALL="en_US.UTF-8"
          mkdir -p cascadiacode
          wget -c ${{ vars.CASCADIACODE_DOWNLOAD_URL }}
          unzip ${{ vars.CASCADIACODE_DOWNLOADED_FILENAME }} -d cascadiacode
          ./build.sh -t cascadiacode/otf/static/CascadiaMono-BoldItalic.otf -o cascadiacode_patched
          ./build.sh -t cascadiacode/otf/static/CascadiaMono-Bold.otf -o cascadiacode_patched
          ./build.sh -t cascadiacode/otf/static/CascadiaMono-ExtraLightItalic.otf -o cascadiacode_patched
          ./build.sh -t cascadiacode/otf/static/CascadiaMono-ExtraLight.otf -o cascadiacode_patched
          ./build.sh -t cascadiacode/otf/static/CascadiaMono-Italic.otf -o cascadiacode_patched
          ./build.sh -t cascadiacode/otf/static/CascadiaMono-LightItalic.otf -o cascadiacode_patched
          ./build.sh -t cascadiacode/otf/static/CascadiaMono-Light.otf -o cascadiacode_patched
          ./build.sh -t cascadiacode/otf/static/CascadiaMono-Regular.otf -o cascadiacode_patched
          ./build.sh -t cascadiacode/otf/static/CascadiaMono-SemiBoldItalic.otf -o cascadiacode_patched
          ./build.sh -t cascadiacode/otf/static/CascadiaMono-SemiBold.otf -o cascadiacode_patched
          ./build.sh -t cascadiacode/otf/static/CascadiaMono-SemiLightItalic.otf -o cascadiacode_patched
          ./build.sh -t cascadiacode/otf/static/CascadiaMono-SemiLight.otf -o cascadiacode_patched
      -
        name: Upload CascadiaCode Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cascadiacode_patched
          path: cascadiacode_patched

